language: rust
sudo: false

cache: cargo

matrix:
    include:
        # Builds with wasm-pack and tests on firefox and chrome.
        - rust: beta
          env: RUST_BACKTRACE=1
          addons:
              firefox: latest
              chrome: stable
          before_script:
              - (test -x $HOME/.cargo/bin/cargo-install-update || cargo install cargo-update)
              - cargo install-update -a
              - curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh -s -- -f
          script:
              - wasm-pack build
              - wasm-pack test --chrome --firefox --headless
